#### add primary imports

In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

#### Load csv 

In [5]:
churn_df = pd.read_csv("ChurnData.csv")
churn_df['churn'] = churn_df['churn'].astype('int')

#### preprocessing 
- Data pre-processing and selection

In [22]:
X = np.asarray(churn_df.drop(['churn'], axis=1))    # all columns - churn
y = np.asarray(churn_df['churn'])
X[0:5]

array([[1.10000e+01, 3.30000e+01, 7.00000e+00, 1.36000e+02, 5.00000e+00,
        5.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 4.40000e+00,
        2.07500e+01, 0.00000e+00, 1.52500e+01, 3.57000e+01, 4.20000e+01,
        2.11450e+02, 1.25000e+02, 1.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 1.00000e+00, 0.00000e+00, 1.48200e+00, 3.03300e+00,
        4.91300e+00, 4.00000e+00],
       [3.30000e+01, 3.30000e+01, 1.20000e+01, 3.30000e+01, 2.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 9.45000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 2.88800e+02,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 2.24600e+00, 3.24000e+00,
        3.49700e+00, 1.00000e+00],
       [2.30000e+01, 3.00000e+01, 9.00000e+00, 3.00000e+01, 1.00000e+00,
        2.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 6.30000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000

#### normalize the dataset

In [23]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673, -0.74922681,
         0.48126577, -0.80905935,  0.06044721,  1.08826163, -0.71940664,
        -0.36132818, -0.55974431,  1.54590766,  1.62368828, -0.88640526,
         1.0944415 ,  1.08347268, -0.88640526, -0.97509593, -0.69987184,
         1.28150384,  1.41630855],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148, -0.23718629,
        -0.84846321, -0.80905935, -0.97385292, -0.56616669, -0.38801572,
        -0.61983235, -0.69284848, -0.64686916, -0.61588176, -0.88640526,
        -0.91370804, -0.92295821, -0.88640526,  0.07226665,  0.03858151,
        -0.60481397, -1.36987221],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148, -0.5565779 ,
        -0.84846321, -0.80905935, -0.97385292, -0.5661

#### Train/Test dataset

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 27) (160,)
Test set: (40, 27) (40,)


#### Modeling (Logistic Regression with Scikit-learn)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

####  predict (using our test set)


In [27]:
yhat = LR.predict(X_test)
print(yhat)
print(y_test)

[0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 0 0 1
 0 0 1]
[0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1
 1 0 0]


##### predict_proba

In [28]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.60722328, 0.39277672],
       [0.61809654, 0.38190346],
       [0.58411229, 0.41588771],
       [0.65417657, 0.34582343],
       [0.57846128, 0.42153872],
       [0.60571723, 0.39428277],
       [0.49465243, 0.50534757],
       [0.63096405, 0.36903595],
       [0.37261192, 0.62738808],
       [0.57501555, 0.42498445],
       [0.43796261, 0.56203739],
       [0.56949003, 0.43050997],
       [0.52659009, 0.47340991],
       [0.38212909, 0.61787091],
       [0.68571532, 0.31428468],
       [0.52974013, 0.47025987],
       [0.49534501, 0.50465499],
       [0.54486783, 0.45513217],
       [0.42671406, 0.57328594],
       [0.58188784, 0.41811216],
       [0.50068924, 0.49931076],
       [0.41069809, 0.58930191],
       [0.80418638, 0.19581362],
       [0.34302289, 0.65697711],
       [0.43713534, 0.56286466],
       [0.75147663, 0.24852337],
       [0.39496994, 0.60503006],
       [0.42173992, 0.57826008],
       [0.53615371, 0.46384629],
       [0.82329995, 0.17670005],
       [0.